name: publish-pypi
on: push

jobs:
  build:
    name: publish-pypi
    runs-on: ubuntu-latest
    # environment:
    #   name: pypi
    #   url: https://pypi.org/p/<your-pypi-project-name>
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Build wheels
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        
        with:
          user: __token__
          password: ${{ secrets.PYPI }}

